# Generated by Django 6.0.2 on 2026-02-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medicine_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importnote',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='importnote',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='importnote',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_exported',
        ),
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='ImportDetail',
        ),
        migrations.DeleteModel(
            name='ImportNote',
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
    ]
