# Generated by Django 6.0.3 on 2026-03-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_importnote_pharmacy_remove_importnote_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
